parser: babel-eslint
extends: airbnb

env:
  node: true,
  browser: true,
  es6: true

rules:
  indent: [2, 4, { SwitchCase: 1 }]
  react/jsx-indent: [2, 4]
  react/jsx-indent-props: [2, 4]
  react/jsx-first-prop-new-line: [2, never]
  react/prop-types: [0]
  react/prefer-stateless-function: [0]
  func-names: [2, 'never']
  arrow-parens: [2, 'as-needed']
  arrow-body-style: [0, 'as-needed']
  no-useless-escape: [0]
  no-useless-computed-key: [0]
  jsx-a11y/no-static-element-interactions: [0]

parserOptions:
  ecmaVersion: 7
  sourceType: 'module'

  ecmaFeatures:
    jsx: true
    experimentalObjectRestSpread: true

settings:
  import/resolver:
    node:
      moduleDirectory: ['node_modules', './src']
